export const CREATE_OBSERVATION = 'CREATE_OBSERVATION';
export const SAVE_IMAGE = 'SAVE_IMAGE';
export const SELECT_SPECIE = 'SELECT_SPECIE';
export const HYDRATE_IMAGE = 'HYDRATE_IMAGE';
export const SET_ACTIVE_DRAFT = 'SET_ACTIVE_DRAFT';
